repo: 'html-rearranger'

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 2
  allCommitted: true
  allSynced: true

html:
  - path: 'index.html'
    locked: true

js:
  - path: 'js/main.js'
    valid: true
    bestPractices: true
    search:
      - 'Below ground veggies'
      - 'Above ground veggies'
      - '\$\('
    searchNot:
      - 'document.write\('
      - 'console.log\('
      - 'alert\('
      - 'prompt\('

screenshots:
  - path: 'index.html'
    sizes: [320]
